client:
  react:
    server: http://localhost:3000

server:
  port: 8081
  servlet:
    context-path: /api
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: myHwxRjxWCDFTNG6amzZ
            client-secret: NLG5A8TGNP
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j7d105.p.ssafy.io:3306/recipenav?serverTimezone=Asia/Seoul
    username: recipenav
    password: navan

  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQL8Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: false  # sql 쿼리를 보여줍니다.
        format_sql: false  # sql query formatting
        use_sql_comments: false  # sql 쿼리의 추가정보를 보여줍니다.
        order_by:
          default_null_ordering: last

jwt:
  key:
    key1: "map all the properties with the specified prefix to an object of ServerProperties"
    key2: "Recall that our app needs to be enabled for configuration properties as well, though this is done automatically in"
    key3: "Despite the fact that both annotations can be used to inject properties from configuration files, they are quite"
    key4: "different. The major difference between these two annotations is that each one serves a different purpose."
    key5: "In this brief article, we discussed how to inject a Map from a YAML file in Spring Boot. Then we highlighted the"


#로그파일 경로
log:
  config:
    path: "/logs/local"
    filename: "auth_log"

logging:
  level:
    root: info
#    org:
#      hibernate:
#        sql: debug
#        type:
#          descriptor:
#            sql: trace

springdoc:
  paths-to-match:
    - /**